// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class Test1 
{
	public static void main(String args[]) throws InterruptedException 
	{
	    //WebDriver driver = new FirefoxDriver();
	    WebDriver driver = new ChromeDriver();
	    
		//System.setProperty("webdriver.gecko.driver",  "/home/myacc/eclipse/jee-neon2/eclipse/geckodriver");
	
	    driver.get("https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1558997388&rver=7.0.6737.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fRpsCsrfState%3dc3838c7e-3ae6-563d-adb6-a14e382b1a0a&id=292841&aadredir=1&whr=hotmail.com&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=90015");
	    driver.findElement(By.id("i0116")).click();
	    
	    //Ingresa correo Outlook
	    driver.findElement(By.id("i0116")).sendKeys("correo@hotmail.com");
	    driver.findElement(By.id("idSIButton9")).click();
	    Thread.sleep(5000);
	    driver.findElement(By.id("i0118")).click();
	    
	    //Ingresar contrasenia
	    driver.findElement(By.id("i0118")).sendKeys("password"); 
	    driver.findElement(By.id("idSIButton9")).click();
	    Thread.sleep(5000);
	    //driver.quit();
    }
}
