package com.enroute;
//Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class Test_gmail 
{
	public static void main(String args[]) throws InterruptedException 
	{
	    WebDriver driver = new ChromeDriver();
	    	
	    driver.get("https://accounts.google.com/ServiceLogin/identifier?elo=1&flowName=GlifWebSignIn&flowEntry=AddSession");
	    
	    // Ingresa correo Outlook
	    driver.findElement(By.id("identifierId")).sendKeys("rockstars.enroute@gmail.com");
	    driver.findElement(By.id("identifierNext")).click();
	    Thread.sleep(3000);
	    
	    // Ingresar contrasenia
	    driver.findElement(By.name("password")).sendKeys("Rockstars2019"); 
	    driver.findElement(By.id("passwordNext")).click();
	    driver.quit();
 }
}

